Repository PAException/engelsburg-api, pull requests merged in 2021-07, with the labels that each got.

#25 set charset to utf-8 in the response headers
  src/main/java/io/github/paexception/engelsburg/api/spring/paging/PagingInterceptor.java
  src/main/java/io/github/paexception/engelsburg/api/util/Result.java
Labels: bug

#28 Fixed tests
  .github/ISSUE_TEMPLATE/bug.md
  .github/ISSUE_TEMPLATE/feature.md
  .github/ISSUE_TEMPLATE/improvement.md
  .github/checkstyle-suppressions.xml
  .github/checkstyle.xml
  .github/workflows/checkstyle.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/maven.yml
  pom.xml
  src/main/java/io/github/paexception/engelsburg/api/EngelsburgAPI.java
  src/main/java/io/github/paexception/engelsburg/api/controller/ArticleController.java
  src/main/java/io/github/paexception/engelsburg/api/controller/AuthenticationController.java
  src/main/java/io/github/paexception/engelsburg/api/controller/EventController.java
  src/main/java/io/github/paexception/engelsburg/api/controller/GradeController.java
  src/main/java/io/github/paexception/engelsburg/api/controller/InformationController.java
  src/main/java/io/github/paexception/engelsburg/api/controller/NotificationController.java
  src/main/java/io/github/paexception/engelsburg/api/controller/SubstituteController.java
  src/main/java/io/github/paexception/engelsburg/api/controller/SubstituteMessageController.java
  src/main/java/io/github/paexception/engelsburg/api/controller/TaskController.java
  src/main/java/io/github/paexception/engelsburg/api/controller/TimetableController.java
  src/main/java/io/github/paexception/engelsburg/api/controller/internal/ScopeController.java
  src/main/java/io/github/paexception/engelsburg/api/controller/internal/TokenController.java
  src/main/java/io/github/paexception/engelsburg/api/controller/userdata/UserDataController.java
  src/main/java/io/github/paexception/engelsburg/api/controller/userdata/UserDataHandler.java
  src/main/java/io/github/paexception/engelsburg/api/endpoint/ArticleEndpoint.java
  src/main/java/io/github/paexception/engelsburg/api/endpoint/AuthenticationEndpoint.java
  src/main/java/io/github/paexception/engelsburg/api/endpoint/EventEndpoint.java
  src/main/java/io/github/paexception/engelsburg/api/endpoint/GradeEndpoint.java
  src/main/java/io/github/paexception/engelsburg/api/endpoint/InformationEndpoint.java
  src/main/java/io/github/paexception/engelsburg/api/endpoint/NotificationEndpoint.java
  src/main/java/io/github/paexception/engelsburg/api/endpoint/OtherEndpoint.java
  src/main/java/io/github/paexception/engelsburg/api/endpoint/SubstituteEndpoint.java
  src/main/java/io/github/paexception/engelsburg/api/endpoint/SubstituteMessageEndpoint.java
  src/main/java/io/github/paexception/engelsburg/api/endpoint/TaskEndpoint.java
  src/main/java/io/github/paexception/engelsburg/api/endpoint/TimetableEndpoint.java
  src/main/java/io/github/paexception/engelsburg/api/endpoint/UserDataEndpoint.java
  src/main/java/io/github/paexception/engelsburg/api/service/email/EmailService.java
  src/main/java/io/github/paexception/engelsburg/api/service/notification/FirebaseCloudMessagingImpl.java
  src/main/java/io/github/paexception/engelsburg/api/service/notification/NotificationService.java
  src/main/java/io/github/paexception/engelsburg/api/service/scheduled/ArticleUpdateService.java
  src/main/java/io/github/paexception/engelsburg/api/service/scheduled/EventUpdateService.java
  src/main/java/io/github/paexception/engelsburg/api/service/scheduled/SubstituteUpdateService.java
  src/main/java/io/github/paexception/engelsburg/api/spring/HashVerifier.java
  src/main/java/io/github/paexception/engelsburg/api/spring/RestControllerExceptionHandler.java
  src/main/java/io/github/paexception/engelsburg/api/spring/WebConfig.java
  src/main/java/io/github/paexception/engelsburg/api/spring/paging/PagingInterceptor.java
  src/main/java/io/github/paexception/engelsburg/api/util/Error.java
  src/main/java/io/github/paexception/engelsburg/api/util/Result.java
Labels: bug

#29 Fixed issue/26
  src/main/java/io/github/paexception/engelsburg/api/controller/AuthenticationController.java
  src/main/java/io/github/paexception/engelsburg/api/database/repository/UserRepository.java
Labels: bug

#32 Improved event fetching
  src/main/java/io/github/paexception/engelsburg/api/service/scheduled/EventUpdateService.java
Labels: improvement

#34 Implemented native adapter for oauth and google oauth implementation
  .docs/endpoints.yaml
  README.md
  pom.xml
  src/main/java/io/github/paexception/engelsburg/api/controller/AuthenticationController.java
  src/main/java/io/github/paexception/engelsburg/api/controller/OAuthController.java
  src/main/java/io/github/paexception/engelsburg/api/controller/oauth/GoogleOAuth2Impl.java
  src/main/java/io/github/paexception/engelsburg/api/controller/oauth/OAuthHandler.java
  src/main/java/io/github/paexception/engelsburg/api/database/model/OAuthModel.java
  src/main/java/io/github/paexception/engelsburg/api/database/repository/OAuthRepository.java
  src/main/java/io/github/paexception/engelsburg/api/endpoint/OAuthEndpoint.java
  src/main/java/io/github/paexception/engelsburg/api/endpoint/dto/request/LoginOAuthRequestDTO.java
  src/main/java/io/github/paexception/engelsburg/api/endpoint/dto/response/OAuthSignupResponseDTO.java
  src/main/java/io/github/paexception/engelsburg/api/service/notification/FirebaseCloudMessagingImpl.java
  src/main/java/io/github/paexception/engelsburg/api/util/Environment.java
Labels: documentation, feature, time consuming

#36 Added cafeteria info
  .docs/endpoints.yaml
  src/main/java/io/github/paexception/engelsburg/api/controller/CafeteriaController.java
  src/main/java/io/github/paexception/engelsburg/api/endpoint/CafeteriaEndpoint.java
  src/main/java/io/github/paexception/engelsburg/api/endpoint/dto/CafeteriaInformationDTO.java
  src/main/java/io/github/paexception/engelsburg/api/service/scheduled/ArticleUpdateService.java
  src/main/java/io/github/paexception/engelsburg/api/service/scheduled/CafeteriaUpdateService.java
  src/main/java/io/github/paexception/engelsburg/api/service/scheduled/SolarSystemUpdateService.java
  src/main/java/io/github/paexception/engelsburg/api/util/WordpressAPI.java
Labels: documentation, feature

#38 Added article specific endpoint
  .docs/endpoints.yaml
  src/main/java/io/github/paexception/engelsburg/api/controller/ArticleController.java
  src/main/java/io/github/paexception/engelsburg/api/database/model/ArticleModel.java
  src/main/java/io/github/paexception/engelsburg/api/endpoint/ArticleEndpoint.java
  src/main/java/io/github/paexception/engelsburg/api/endpoint/dto/ArticleDTO.java
  src/main/java/io/github/paexception/engelsburg/api/service/scheduled/ArticleUpdateService.java
Labels: documentation, improvement

#42 Added blur hashes
  .docs/endpoints.yaml
  .github/checkstyle.xml
  pom.xml
  src/main/java/io/github/paexception/engelsburg/api/EngelsburgAPI.java
  src/main/java/io/github/paexception/engelsburg/api/controller/internal/ErrorController.java
  src/main/java/io/github/paexception/engelsburg/api/controller/reserved/InformationController.java
  src/main/java/io/github/paexception/engelsburg/api/controller/shared/ArticleController.java
  src/main/java/io/github/paexception/engelsburg/api/database/model/ArticleModel.java
  src/main/java/io/github/paexception/engelsburg/api/endpoint/dto/ArticleDTO.java
  src/main/java/io/github/paexception/engelsburg/api/endpoint/dto/CafeteriaInformationDTO.java
  src/main/java/io/github/paexception/engelsburg/api/service/scheduled/ArticleUpdateService.java
  src/main/java/io/github/paexception/engelsburg/api/service/scheduled/CafeteriaUpdateService.java
  src/main/java/io/github/paexception/engelsburg/api/util/LoggingComponent.java
  src/main/java/io/github/paexception/engelsburg/api/util/Result.java
  src/main/java/io/github/paexception/engelsburg/api/util/WordpressAPI.java
Labels: documentation, improvement
